name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tdd/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 tdd/tests/test_counter.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 tdd/tests/test_counter.py --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Static code analysis with Bandit
        run: bandit -r tdd/src/

      - name: Run unit tests with nose
        working-directory: tdd/
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app